//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimerLaboratorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotasEstudiante
    {
        public int Est_id { get; set; }
        public string Est_nombre { get; set; }
        public string Est_lab1 { get; set; }
        public string Est_lab2 { get; set; }
        public string Est_lab3 { get; set; }
        public string Est_par1 { get; set; }
        public string Est_par2 { get; set; }
        public string Est_par3 { get; set; }
    }
}
